# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BountyStats',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stats_date', models.DateField()),
                ('bounties_issued', models.IntegerField(default=0)),
                ('fulfillments_submitted', models.IntegerField(default=0)),
                ('fulfillments_accepted', models.IntegerField(default=0)),
                ('fulfillments_not_accepted', models.IntegerField(default=0)),
                ('draft_bounties', models.IntegerField(default=0)),
                ('active_bounties', models.IntegerField(default=0)),
                ('dead_bounties', models.IntegerField(default=0)),
                ('completed_bounties', models.IntegerField(default=0)),
                ('exprired_bounties', models.IntegerField(default=0)),
            ],
        ),
    ]
